# Generated by Django 4.2 on 2025-08-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ManyToManyField(related_name='choices', to='polls.question'),
        ),
    ]
